config/routes.rb
Jailtester::Application.routes.draw do
  resources :submissions

  get 'status/:mongoid(.:format)', to: 'submissions#submission_status', as: :status
  post 'submit(.:format)', to: 'submissions#custom_create'

  get 'rerun/:id(.:format)', to: 'submissions#rerun', as: :rerun

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  include SubmissionsHelper
  attr_accessible :filespath, :email, :log, :mongoId, :stderr, :stdout, :result

  validates_uniqueness_of :mongoId

  def run_checker
    res = run_code(self.filespath)
    self.stdout = res[:stdout]
    self.stderr = res[:stderr]
    self.log += res[:log]
    self.result = res[:result]

    self.save!
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  include FileHelper
  # GET /submissions
  # GET /submissions.json
  def index
    if params[:email]
      @submissions = Submission.find_all_by_email(params[:email])
    else
      @submissions = Submission.all
    end


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @submissions }
    end
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    @submission = Submission.find(params[:id])
    @files = read_files @submission.filespath
    @description = read_description @submission.filespath

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @submission }
    end
  end

  # GET /submissions/new
  # GET /submissions/new.json
  def new
    @submission = Submission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @submission }
    end
  end

  # GET /submissions/1/edit
  def edit
    @submission = Submission.find(params[:id])
  end

  # POST /submissions
  # POST /submissions.json
  def create
    unzip = unzip_and_store(params[:submission][:upload], params[:submission][:train], params[:submission][:email])
    result = unzip[:log].empty? ? 'Processing upload' : 'Error occurred'
    @submission = Submission.new(mongoId: params[:submission][:mongoId],
                                 email: params[:submission][:email],
                                 filespath: unzip[:dir],
                                 log: unzip[:log],
                                 result: result
    )

    respond_to do |format|
      if @submission.save
        @submission.delay.run_checker if unzip[:log].empty?
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render json: @submission, status: :created, location: @submission }
      else
        format.html { render action: "new" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def custom_create
    unzip = get_and_store(params[:submission][:upload], params[:submission][:train], params[:submission][:email])
    result = unzip[:log].empty? ? 'Processing upload' : 'Error occurred'
    @submission = Submission.new(mongoId: params[:submission][:mongoId],
                                 email: params[:submission][:email],
                                 filespath: unzip[:dir],
                                 log: unzip[:log],
                                 result: result
    )

    respond_to do |format|
      if @submission.save
        @submission.delay.run_checker if unzip[:log].empty?
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render json: @submission, status: :created, location: @submission }
      else
        format.html { render action: "new" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def rerun
    @submission = Submission.find(params[:id])
    @submission.delay.run_checker

    redirect_to @submission, notice: 'Rerun in progress'
  end

  # PUT /submissions/1
  # PUT /submissions/1.json
  def update
    @submission = Submission.find(params[:id])

    respond_to do |format|
      if @submission.update_attributes(params[:submission])
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to submissions_url }
      format.json { head :no_content }
    end
  end

  def grab_result(sub)
    puts sub
    return 'Not found' if sub.nil?
    return sub.result if sub.email != 'baseline2@ispras.ru'
    format('%.10f', sub.result.to_f + 0.0000000001)
  end

  def submission_status
    submission = Submission.find_by_mongoId(params[:mongoid])
    @result = grab_result submission
    response.headers['Access-Control-Allow-Origin'] = '*'
    respond_to do |format|
      format.html
      format.json { render json: {result: @result} }
    end
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
  require 'open3'

  def run_code(dir, maxt=6)
    Open3.capture2(Rails.configuration.access_cmd + ' rm -rf ' + Rails.configuration.jail_dir + '/*')
    sleep 3
    Open3.capture2(Rails.configuration.access_cmd + ' cp -r ' + dir + '/* ' + Rails.configuration.jail_dir)
    Open3.capture2(Rails.configuration.access_cmd + ' cp -r ' + Rails.configuration.eval_dir + '/* ' + Rails.configuration.jail_dir)
    sleep 3

    cmd = Rails.configuration.jailbox_cmd
    evaler = Rails.configuration.jail_dir + '/eval.py'
    train_set = Rails.configuration.jail_dir + '/train.json'
    test_set = Rails.configuration.jail_dir + '/test_corpus.json'

    Dir.chdir(Rails.configuration.jail_dir + '/archive'){
      out = run('%s %s %s %s 2>&1' % [cmd, evaler, train_set, test_set], Rails.configuration.jail_dir + '/archive', 20*60)
      if out[:success]
        result = /(?<=Accuracy: )(.*)$/.match(out[:out]).to_s
      else
        result = 'Error occurred'
      end

      {
          stdout: out[:out],
          stderr: out[:errmesg],
          log: out[:out],
          result: result
      }
    }
  end

  def run(s, dir, maxt = 10*60)
    success, errmesg = true, ''
    begin
      pipe = IO.popen(s, chdir: dir)

      begin
        Timeout::timeout(maxt) do |t|
          a = Process.waitpid2(pipe.pid)
          if a[1].exitstatus != 0
            success = false
            errmesg = 'Execution failed'
          end
        end
      rescue Timeout::Error => e
        begin
          Process.kill('TERM', pipe.pid)
        rescue Object => e
          success = false
          errmesg = 'Execution has timed out, no kill'
        end
        success = false
        errmesg = 'Execution has timed out'
      end
    rescue Exception => e
      success = false
      errmesg = 'Execution failed: ' + e.to_s
    end

    out = pipe.gets(nil)
    pipe.close
    {
        success: success,
        errmesg: errmesg,
        out: out.to_s
    }
  end

end

app/views/submissions/_form.html.erb
<%= form_for(@submission) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mongoId %><br />
    <%= f.text_field :mongoId %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label 'Zip' %><br />
    <%= f.file_field 'upload' %>
  </div>

    <div class="field">
      <%= f.label 'JSON' %><br />
      <%= f.file_field 'train' %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<h1>Listing submissions</h1>

<input id="filter" type="text" class="form-control" placeholder="Filter"/>

<table class="table table-stripped">
  <thead>
  <tr>
    <th>Mongoid</th>
    <th>Email</th>
    <th>Result</th>
    <th>Added</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @submissions.each do |submission| %>
      <tr>
        <td class="mongoid">
          <%= submission.mongoId.length == 17 ? '' : 'mass ' %><%= link_to submission.mongoId, submission %>
        </td>
        <td><%= submission.email %></td>
        <td><%= submission.result %></td>
        <td><%= submission.created_at %></td>
        <td>
          <div class="btn-group">
            <%= link_to 'Show', submission, class: 'btn btn-default' %>
            <%= link_to 'Destroy', submission, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Submission', new_submission_path, class: 'btn btn-default' %>

app/views/submissions/new.html.erb
<h1>New submission</h1>

<%= render 'form' %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <p>
    <b>Mongoid:</b>
    <%= @submission.mongoId %>
  </p>

  <p>
    <b>Email:</b>
    <%= @submission.email %>
  </p>

  <p>
    <b>Result:</b>
    <%= @submission.result %>
  </p>

  <%= link_to 'Back', submissions_path, class: 'btn btn-default' %>
  <%= link_to 'Rerun', rerun_path(@submission), class: 'btn btn-primary'%>
  <%= link_to 'Destroy', @submission, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger' %>
</div>
</br>

<div class="panel panel-default">
  <div class="panel-heading">Description</div>
  <div class="panel-body">
    <% @description.each do |file| %>
        <div class="code_file">
          <b><%= file[:name] %></b>
          <pre><%=raw file[:content] %></pre>
        </div>

    <% end %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Files</div>
  <div class="panel-body">
    <% @files.each do |file| %>
        <div class="code_file">
          <b><%= file[:name] %></b>
          <pre><code class="python"><%=raw file[:content] %></code></pre>
        </div>
    <% end %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Output(stdout+stderr)</div>
  <pre><code class="python"><%= @submission.stdout %></code></pre>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Error explanation</div>
  <pre><code class="python"><%= @submission.stderr %></code></pre>
</div>

<div class="panel panel-default">
  <div class="panel-heading">Log</div>
  <pre><code class="python"><%= @submission.log %></code></pre>
</div>

<link rel="stylesheet" href="/assets/styles/googlecode.css">
<script src="/assets/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

app/views/submissions/submission_status.html.erb
<%= @result %>